name: Nightly Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  performance_tests:
    name: Profilowanie i wysyłka do Grafany
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4
