name: Rov Controller Nightly Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  code-quality-check:
    name: Code Quality
    uses: ./.github/workflows/reusable-code-quality.yaml
    secrets: inherit
    with:
      upload_to_grafana: true
